import type { City } from "./types";

const U = "2026-09-27";

export const citiesMore: City[] = [
  {
    slug: "avondale",
    name: "Avondale",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "west",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85323", "85392"],
    areas: ["Historic Avondale", "Garden Lakes", "Coldwater Springs", "Rancho Santa Fe", "Crystal Gardens"],
    intro:
      "Avondale mixes an older core near Western Avenue with large subdivisions built in the late 1990s and 2000s, like Garden Lakes and Coldwater Springs. The newer homes are too young for polybutylene, so the common calls are hard-water damage, water heaters at the end of their first life, and slab or irrigation leaks.",
    housingNotes:
      "Most of Avondale's housing dates from about 1995 onward, with copper or PEX supply lines and many garage softener loops. The historic area near the Agua Fria River has older, smaller homes with galvanized and cast iron piping. Lake communities have large shared irrigation and backflow systems.",
    localIssues: [
      { title: "First-generation water heaters", body: "Homes from the 2000s boom are on their first or second tank, and hard water is wearing them out. See [water heater replacement](/plumbing-services/water-heater-replacement/)." },
      { title: "Irrigation leaks", body: "Desert landscaping on newer lots means long drip and mainline runs." },
      { title: "Heat on outdoor plumbing", body: "Exposed hose bibs and lines take a beating from West Valley summer heat and UV." },
    ],
    popularServices: ["water-heater-replacement", "water-softener-installation", "irrigation-leak-repair", "slab-leak-detection", "drain-cleaning", "pressure-regulator-valve"],
    nearby: ["goodyear", "litchfield-park", "glendale", "phoenix"],
    water: "The City of Avondale supplies water, largely from groundwater and CAP surface water.",
    permits: "The City of Avondale Development Services department issues plumbing permits.",
    faqs: [
      { q: "Who issues plumbing permits in Avondale?", a: "The City of Avondale Development Services department." },
      { q: "Are Avondale homes likely to have polybutylene?", a: "Most were built after polybutylene fell out of use, but older homes near the historic core should be checked." },
    ],
    updated: U,
  },
  {
    slug: "goodyear",
    name: "Goodyear",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "west",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85338", "85395"],
    areas: ["Palm Valley", "PebbleCreek", "Estrella", "Canyon Trails", "Centerra", "Wildflower Ranch"],
    intro:
      "Goodyear is one of the fastest-growing West Valley cities, with most homes built since the late 1990s in communities like Palm Valley, PebbleCreek and Estrella. Plumbing here is newer, but Valley hard water, garage heat and big irrigated lots still generate a steady stream of water heater, softener and leak calls.",
    housingNotes:
      "Nearly all of Goodyear's housing uses copper or PEX supply lines and slab foundations, often with softener loops and recirculation-ready plumbing. Estrella's hillside lots and PebbleCreek's age-restricted community each bring their own mix of irrigation, backflow and water heater work.",
    localIssues: [
      { title: "Water provider varies", body: "Depending on the neighborhood, water may come from the City of Goodyear or a private utility, and hardness varies with the source. See [water softener installation](/plumbing-services/water-softener-installation/)." },
      { title: "Tankless maintenance", body: "Newer homes with tankless heaters need regular descaling in hard water." },
      { title: "Backflow on large systems", body: "HOA-landscaped communities have many backflow assemblies that need testing and freeze protection." },
    ],
    popularServices: ["water-softener-installation", "tankless-water-heaters", "water-heater-flush", "backflow-testing", "irrigation-leak-repair", "hot-water-recirculation"],
    nearby: ["avondale", "litchfield-park", "surprise"],
    water: "The City of Goodyear serves much of the city; some communities are served by private utilities such as Liberty or EPCOR. Your bill shows the provider.",
    permits: "The City of Goodyear Building Safety division issues plumbing permits.",
    faqs: [
      { q: "Who supplies water in Goodyear?", a: "The City of Goodyear serves many neighborhoods, and private utilities serve others. Check your water bill." },
      { q: "Do Goodyear homes have softener loops?", a: "Many do, since most were built after the late 1990s. Look for capped pipes near the water heater in the garage." },
    ],
    updated: U,
  },
  {
    slug: "litchfield-park",
    name: "Litchfield Park",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "west",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85340"],
    areas: ["Old Litchfield", "Wigwam area", "Litchfield Greens", "Village at Litchfield Park"],
    intro:
      "Litchfield Park is a small, tree-lined city that began as a company town for Goodyear Tire's cotton operations in the early 20th century. Its older homes near the Wigwam sit alongside newer subdivisions, and mature trees make it one of the few Valley towns where roots in sewer and irrigation lines are a regular issue.",
    housingNotes:
      "The original core has some of the West Valley's oldest homes, with galvanized pipe and clay or cast iron sewer laterals. Surrounding subdivisions date from the 1980s through the 2000s. Large lots and old palms, citrus and shade trees mean extensive irrigation and root pressure on buried lines.",
    localIssues: [
      { title: "Roots in older sewer lines", body: "Mature trees send roots into clay and cast iron laterals. See [sewer camera inspection](/plumbing-services/sewer-camera-inspection/)." },
      { title: "Older supply piping", body: "Homes in the original town core may still have galvanized supply lines." },
      { title: "Irrigation on large lots", body: "Flood and drip irrigation for mature landscaping keeps backflow assemblies busy." },
    ],
    popularServices: ["sewer-camera-inspection", "drain-cleaning", "sewer-line-repair", "whole-house-repiping", "backflow-testing", "water-heater-replacement"],
    nearby: ["goodyear", "avondale", "glendale"],
    water: "Liberty Utilities (Litchfield Park Service Company) supplies water and sewer service to much of the area.",
    permits: "The City of Litchfield Park issues building and plumbing permits.",
    faqs: [
      { q: "Why do Litchfield Park homes get root clogs?", a: "The city has more mature trees than most of the Valley, and roots find cracks in older clay and cast iron sewer lines." },
      { q: "Who provides water in Litchfield Park?", a: "Liberty Utilities serves much of the city. Check your bill to confirm." },
    ],
    updated: U,
  },
  {
    slug: "surprise",
    name: "Surprise",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "northwest",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85374", "85378", "85379", "85387", "85388"],
    areas: ["Original Town Site", "Sun City Grand", "Marley Park", "Surprise Farms", "Kingswood Parke", "Asante"],
    intro:
      "Surprise grew from a small farm town into a large Northwest Valley city, mostly after 2000. Age-restricted Sun City Grand and family communities like Marley Park and Surprise Farms dominate, so the plumbing is mostly copper or PEX. The main issues are hard water, water heaters and pressure.",
    housingNotes:
      "The small original town site near Grand Avenue has older homes. Nearly everything else was built from the late 1990s on, typically with softener loops and slab foundations. Sun City Grand homes from around 1996–2005 are now at the age for water heater replacement, PRV failure and early copper pinholes.",
    localIssues: [
      { title: "PRV and water heater age", body: "Homes from the late 1990s and early 2000s are hitting the end of life for pressure regulators and water heaters. See [pressure regulator replacement](/plumbing-services/pressure-regulator-valve/)." },
      { title: "Hard water", body: "Softener loops are common, and a softener protects newer tankless heaters." },
      { title: "Irrigation", body: "Large desert-landscaped lots rely on drip irrigation and backflow assemblies." },
    ],
    popularServices: ["water-heater-replacement", "pressure-regulator-valve", "water-softener-installation", "slab-leak-detection", "irrigation-leak-repair", "tankless-water-heaters"],
    nearby: ["sun-city-west", "sun-city", "peoria", "goodyear"],
    water: "The City of Surprise supplies water to many neighborhoods; EPCOR serves others, including parts of Sun City Grand.",
    permits: "The City of Surprise issues plumbing permits.",
    faqs: [
      { q: "Who supplies water in Surprise?", a: "Depending on the neighborhood, the City of Surprise or EPCOR. Check your bill." },
      { q: "Who issues plumbing permits in Surprise?", a: "The City of Surprise building division." },
    ],
    updated: U,
  },
  {
    slug: "sun-city",
    name: "Sun City",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "northwest",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85351", "85373"],
    areas: ["Phase I (south of Grand Ave)", "Bell Road corridor", "Lakeview", "Viewpoint Lake area"],
    intro:
      "Sun City opened in 1960 as Del Webb's first active-adult community, and most of its homes were built through the 1960s and 70s. That makes much of its plumbing 45 to 65 years old: copper and some galvanized supply, cast iron drains under the slab, and main lines and sewer laterals that are reaching the end of their life.",
    housingNotes:
      "Homes are mostly single-story ranches and patio homes on slabs, many still with original or partly updated plumbing. Cast iron drain lines under the slab are a common repair, as are copper pinhole leaks and water heater replacements in tight garage or utility-room spaces.",
    localIssues: [
      { title: "Cast iron drains under the slab", body: "After decades of use, cast iron drains scale and crack. See [sewer camera inspection](/plumbing-services/sewer-camera-inspection/)." },
      { title: "Aging copper", body: "Pinhole leaks in older copper point toward a repipe." },
      { title: "Unincorporated permits", body: "Sun City is unincorporated, so permits go through Maricopa County, not a city." },
    ],
    popularServices: ["sewer-camera-inspection", "sewer-line-repair", "pinhole-leak-repair", "whole-house-repiping", "water-heater-replacement", "drain-cleaning"],
    nearby: ["sun-city-west", "peoria", "surprise", "glendale"],
    water: "EPCOR supplies water to Sun City.",
    permits: "Sun City is unincorporated, so Maricopa County Planning & Development issues plumbing permits.",
    faqs: [
      { q: "Who issues plumbing permits in Sun City?", a: "Maricopa County, because Sun City is unincorporated." },
      { q: "Are cast iron drains a problem in Sun City homes?", a: "Often, given their age. A camera inspection shows the condition before any repair decision." },
    ],
    updated: U,
  },
  {
    slug: "sun-city-west",
    name: "Sun City West",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "northwest",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85375"],
    areas: ["Original phases (1978–1985)", "Mid phases (1985–1992)", "Later phases (1992–1998)", "RH Johnson corridor"],
    intro:
      "Sun City West was built by Del Webb from 1978 through the late 1990s as the follow-on to Sun City. Its build-out lines up almost exactly with the years polybutylene supply pipe was popular, so repiping is the signature plumbing job in this community, along with water heaters and pressure regulators.",
    housingNotes:
      "Homes are single-story on slabs with attic access, which suits overhead PEX repipes. Earlier phases are now more than 40 years old, with original water heaters long gone and some PRVs and main shutoffs overdue.",
    localIssues: [
      { title: "Polybutylene", body: "Many homes from the build-out years have or had polybutylene. See [polybutylene replacement](/plumbing-services/polybutylene-replacement/)." },
      { title: "Unincorporated permits", body: "Maricopa County handles permits here, not a city." },
      { title: "Pressure regulators", body: "Older PRVs let pressure creep up, stressing aging supply lines." },
    ],
    popularServices: ["whole-house-repiping", "polybutylene-replacement", "water-heater-replacement", "pressure-regulator-valve", "water-softener-installation", "drain-cleaning"],
    nearby: ["sun-city", "surprise", "peoria"],
    water: "EPCOR supplies water to Sun City West.",
    permits: "Sun City West is unincorporated, so Maricopa County Planning & Development issues plumbing permits.",
    faqs: [
      { q: "How do I know if my Sun City West home has polybutylene?", a: "Look at the pipe coming out of the wall at the water heater and under sinks for gray pipe stamped PB2110." },
      { q: "Who issues plumbing permits in Sun City West?", a: "Maricopa County, because the community is unincorporated." },
    ],
    updated: U,
  },
  {
    slug: "mesa",
    name: "Mesa",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "east",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85201", "85202", "85203", "85204", "85205", "85206", "85207", "85208", "85209", "85210", "85212", "85213", "85215"],
    areas: ["Downtown Mesa", "Dobson Ranch", "Red Mountain", "Las Sendas", "Eastmark", "Superstition Springs", "Lehi"],
    intro:
      "Mesa is the Valley's second-largest city, with mid-century homes near downtown, big 1970s–90s subdivisions like Dobson Ranch, and newer communities in east Mesa like Eastmark and Las Sendas. It also has a feature few Valley cities share: parts of Mesa get natural gas from the City of Mesa's own utility instead of Southwest Gas.",
    housingNotes:
      "Central and west Mesa have 1950s–70s homes with galvanized and cast iron piping. The 1978–1995 building boom across much of Mesa means polybutylene is common. East Mesa's newer homes have copper or PEX with softener loops.",
    localIssues: [
      { title: "Polybutylene", body: "Much of Mesa's housing dates from the polybutylene years. See [whole-house repiping](/plumbing-services/whole-house-repiping/)." },
      { title: "Two gas utilities", body: "Parts of Mesa use the City of Mesa gas utility, which matters for gas line work and emergencies." },
      { title: "Older drains", body: "Downtown-area homes have aging cast iron drains and clay laterals." },
    ],
    popularServices: ["whole-house-repiping", "polybutylene-replacement", "slab-leak-detection", "water-heater-replacement", "gas-line-repair", "drain-cleaning"],
    nearby: ["tempe", "gilbert", "chandler"],
    water: "The City of Mesa supplies water from SRP surface water, CAP Colorado River water, and groundwater.",
    permits: "The City of Mesa Development Services department issues plumbing permits.",
    faqs: [
      { q: "Who do I call if I smell gas in Mesa?", a: "Leave the home and call 911, then your gas provider: the City of Mesa gas utility or Southwest Gas, depending on your address." },
      { q: "Who issues plumbing permits in Mesa?", a: "The City of Mesa Development Services department." },
    ],
    updated: U,
  },
  {
    slug: "tempe",
    name: "Tempe",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "east",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85281", "85282", "85283", "85284"],
    areas: ["Maple-Ash", "Daley Park", "Lakeshore", "The Lakes", "Kiwanis Park area", "South Tempe"],
    intro:
      "Tempe is a landlocked, mostly built-out city around Arizona State University. Its north half is full of 1950s–70s ranch homes, and south Tempe grew in the 1970s and 80s. Lots of rentals and older homes mean repipes, drain problems and water heater swaps are constant.",
    housingNotes:
      "North Tempe neighborhoods such as Maple-Ash and Daley Park have older homes with galvanized supply lines and cast iron or clay sewer laterals. The Lakes and south Tempe grew in the 1970s and 80s, putting some homes in the polybutylene years. Many properties are rentals whose plumbing gets patched rather than replaced.",
    localIssues: [
      { title: "Galvanized supply", body: "Rusty water and low pressure from galvanized lines in older north Tempe homes. See [whole-house repiping](/plumbing-services/whole-house-repiping/)." },
      { title: "Rental turnover", body: "Landlords often need fast water heater swaps and drain clearing between tenants." },
      { title: "Older sewer laterals", body: "Clay and cast iron laterals in older neighborhoods crack and collect roots." },
    ],
    popularServices: ["whole-house-repiping", "drain-cleaning", "water-heater-replacement", "sewer-camera-inspection", "slab-leak-detection", "pressure-regulator-valve"],
    nearby: ["mesa", "chandler", "phoenix", "scottsdale"],
    water: "The City of Tempe supplies water from Salt and Verde river water, CAP water, and groundwater.",
    permits: "The City of Tempe Community Development department issues plumbing permits.",
    faqs: [
      { q: "Who issues plumbing permits in Tempe?", a: "The City of Tempe Community Development department." },
      { q: "Are older Tempe homes worth a sewer camera inspection?", a: "Yes, especially before buying. Many laterals in north Tempe are decades old." },
    ],
    updated: U,
  },
  {
    slug: "chandler",
    name: "Chandler",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "east",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85224", "85225", "85226", "85248", "85249", "85286"],
    areas: ["Downtown Chandler", "Ocotillo", "Fulton Ranch", "Sun Groves", "Andersen Springs", "Cooper Commons"],
    intro:
      "Chandler grew from a farming town into a tech-industry suburb, with most of its homes built from the 1980s through the 2000s. The older central neighborhoods fall into the polybutylene years, and newer south Chandler communities like Ocotillo and Fulton Ranch deal mostly with hard water, water heaters and irrigation.",
    housingNotes:
      "Central Chandler's 1980s and early-90s homes may have polybutylene or aging copper. South Chandler's newer homes typically have copper or PEX with softener loops. Ocotillo's lake-lot homes and larger south Chandler lots carry big irrigation systems with backflow assemblies.",
    localIssues: [
      { title: "Polybutylene in 1980s homes", body: "Central Chandler neighborhoods fall into the polybutylene window. See [polybutylene replacement](/plumbing-services/polybutylene-replacement/)." },
      { title: "Hard water", body: "Softeners and RO systems are common upgrades in newer south Chandler homes." },
      { title: "Irrigation and backflow", body: "Large landscaped lots mean backflow tests and mainline leaks." },
    ],
    popularServices: ["polybutylene-replacement", "water-softener-installation", "reverse-osmosis-systems", "water-heater-replacement", "backflow-testing", "slab-leak-detection"],
    nearby: ["gilbert", "tempe", "mesa"],
    water: "The City of Chandler supplies water from SRP surface water, CAP water, and groundwater.",
    permits: "The City of Chandler Development Services department issues plumbing permits.",
    faqs: [
      { q: "Who issues plumbing permits in Chandler?", a: "The City of Chandler Development Services department." },
      { q: "Should I repipe a 1980s Chandler home?", a: "If it has polybutylene or has had several copper leaks, a repipe is worth pricing." },
    ],
    updated: U,
  },
  {
    slug: "gilbert",
    name: "Gilbert",
    stateSlug: "arizona",
    county: "Maricopa",
    region: "east",
    status: "PUBLISHED",
    officeAddress: null,
    zips: ["85233", "85234", "85295", "85296", "85297", "85298"],
    areas: ["Heritage District", "Val Vista Lakes", "Power Ranch", "Agritopia", "Seville", "Morrison Ranch"],
    intro:
      "Gilbert went from a farm town to one of the largest towns in the country during the 1990s and 2000s boom, so most homes are 20 to 30 years old. That age brings first water heater replacements, failing pressure regulators, and early copper slab leaks, all on top of Valley hard water.",
    housingNotes:
      "Val Vista Lakes and north Gilbert date from the late 1980s and 1990s. Power Ranch, Seville and Morrison Ranch are mostly 2000s construction with copper or PEX and softener loops. The small Heritage District holds Gilbert's oldest homes.",
    localIssues: [
      { title: "Twenty-year-old systems", body: "Water heaters, PRVs and softeners from the boom years are wearing out together. See [pressure regulator replacement](/plumbing-services/pressure-regulator-valve/)." },
      { title: "Copper slab leaks", body: "Homes from the late 1990s are starting to see hot-line slab leaks." },
      { title: "Hard water", body: "Softener loops are standard; many homes never had a unit installed." },
    ],
    popularServices: ["water-heater-replacement", "pressure-regulator-valve", "water-softener-installation", "slab-leak-detection", "hot-water-recirculation", "tankless-water-heaters"],
    nearby: ["chandler", "mesa", "tempe"],
    water: "The Town of Gilbert supplies water from SRP and CAP surface water plus groundwater.",
    permits: "The Town of Gilbert Development Services department issues plumbing permits.",
    faqs: [
      { q: "Who issues plumbing permits in Gilbert?", a: "The Town of Gilbert Development Services department." },
      { q: "Is my Gilbert water heater due for replacement?", a: "If it's over about 10 years old and the home has no softener, it's worth having it checked." },
    ],
    updated: U,
  },
];
